---
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: php-cbf
        name: Fix php code with php-cbf
        language: system
        entry: phpcbf
        verbose: true
        stages: [manual]
        types: [php]
        args: [-n]
  - repo: local
    hooks:
      - id: php-cs
        name: Check php code style with php-cs
        language: system
        entry: phpcs
        verbose: true
        types: [php]
        args: [-n]
